#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_ROOT}"

./scripts/start-docker.sh

LOCAL_SERVER_PORT="${SERVER_PORT:-10002}"
LOCAL_CONTEXT_PATH="${SERVER_SERVLET_CONTEXT_PATH:-/eftboard-server}"
LOCAL_MYSQL_HOST="${MYSQL_HOST:-127.0.0.1}"
LOCAL_MYSQL_PORT="${MYSQL_PORT:-3306}"
LOCAL_MYSQL_DATABASE="${MYSQL_DATABASE:-tarkov_board}"

echo
echo "Starting backend on http://127.0.0.1:${LOCAL_SERVER_PORT}${LOCAL_CONTEXT_PATH}"
echo "Local MySQL: ${LOCAL_MYSQL_HOST}:${LOCAL_MYSQL_PORT}/${LOCAL_MYSQL_DATABASE}"
echo

SERVER_PORT="${LOCAL_SERVER_PORT}" \
SERVER_SERVLET_CONTEXT_PATH="${LOCAL_CONTEXT_PATH}" \
MYSQL_HOST="${LOCAL_MYSQL_HOST}" \
MYSQL_PORT="${LOCAL_MYSQL_PORT}" \
MYSQL_DATABASE="${LOCAL_MYSQL_DATABASE}" \
mvn spring-boot:run
